export type Monomer = {
  id: number;
  prefix: "MC" | "MX";
  name: string;
  family: string;
  signature: string;
  description: string;
};

export type FamilyName = keyof typeof FAMILIES;

export const FAMILIES = {
  Arithmetic: ["ADD", "SUB", "MUL", "DIV", "MOD", "POW", "NEG", "ABS"],
  Logic: ["AND", "OR", "XOR", "NOT", "SHL", "SHR", "ROL", "ROR"],
  Memory: ["LOAD", "STORE", "ALLOC", "FREE", "COPY", "DUP", "SWAP", "DROP"],
  Control: ["IF", "LOOP", "CALL", "RET", "JUMP", "HALT", "NOP", "ASSERT"],
  "I/O": ["READ", "WRITE", "OPEN", "CLOSE", "SEEK", "FLUSH", "STDIN", "STDOUT"],
  String: ["STR", "CONCAT", "SPLIT", "TRIM", "UPPER", "LOWER", "LEN", "CHAR"],
  Crypto: ["HASH", "ENC", "DEC", "SIGN", "VRFY", "RNG", "KDF", "HMAC"],
  System: ["TIME", "ENV", "EXIT", "SPAWN", "WAIT", "SEND", "RECV", "LOG"],
} as const;

export const CORE_MONOMERS: Monomer[] = [
  { id: 0, prefix: "MC", name: "ADD", family: "Arithmetic", signature: "i64, i64 → i64", description: "Standard 64-bit integer addition with overflow wrapping." },
  { id: 1, prefix: "MC", name: "SUB", family: "Arithmetic", signature: "i64, i64 → i64", description: "Standard 64-bit integer subtraction." },
  { id: 2, prefix: "MC", name: "MUL", family: "Arithmetic", signature: "i64, i64 → i64", description: "Standard 64-bit integer multiplication." },
  { id: 3, prefix: "MC", name: "DIV", family: "Arithmetic", signature: "i64, i64 → i64", description: "Integer division. Traps on division by zero." },
  { id: 4, prefix: "MC", name: "MOD", family: "Arithmetic", signature: "i64, i64 → i64", description: "Modulo operator. Result has the same sign as divisor." },
  { id: 5, prefix: "MC", name: "POW", family: "Arithmetic", signature: "i64, i64 → i64", description: "Integer exponentiation." },
  { id: 6, prefix: "MC", name: "NEG", family: "Arithmetic", signature: "i64 → i64", description: "Two's complement negation." },
  { id: 7, prefix: "MC", name: "ABS", family: "Arithmetic", signature: "i64 → i64", description: "Absolute value of a 64-bit integer." },
  { id: 8, prefix: "MC", name: "AND", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise AND operation." },
  { id: 9, prefix: "MC", name: "OR", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise OR operation." },
  { id: 10, prefix: "MC", name: "XOR", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise XOR operation." },
  { id: 11, prefix: "MC", name: "NOT", family: "Logic", signature: "i64 → i64", description: "Bitwise NOT operation." },
  { id: 12, prefix: "MC", name: "SHL", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise shift left." },
  { id: 13, prefix: "MC", name: "SHR", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise shift right (arithmetic)." },
  { id: 14, prefix: "MC", name: "ROL", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise rotate left." },
  { id: 15, prefix: "MC", name: "ROR", family: "Logic", signature: "i64, i64 → i64", description: "Bitwise rotate right." },
  { id: 16, prefix: "MC", name: "LOAD", family: "Memory", signature: "addr → i64", description: "Reads a 64-bit value from a specific memory address." },
  { id: 17, prefix: "MC", name: "STORE", family: "Memory", signature: "addr, i64 → void", description: "Writes a 64-bit value to a specific memory address." },
  { id: 18, prefix: "MC", name: "ALLOC", family: "Memory", signature: "size → addr", description: "Allocates a strictly bounded memory block." },
  { id: 19, prefix: "MC", name: "FREE", family: "Memory", signature: "addr → void", description: "Releases an allocated memory block." },
  { id: 20, prefix: "MC", name: "COPY", family: "Memory", signature: "addr, addr, size → void", description: "Bounded memory block clone/copy." },
  { id: 21, prefix: "MC", name: "DUP", family: "Memory", signature: "i64 → i64, i64", description: "Duplicates the top value on the stack." },
  { id: 22, prefix: "MC", name: "SWAP", family: "Memory", signature: "i64, i64 → i64, i64", description: "Swaps the top two values on the stack." },
  { id: 23, prefix: "MC", name: "DROP", family: "Memory", signature: "i64 → void", description: "Discards the top value on the stack." },
  { id: 24, prefix: "MC", name: "IF", family: "Control", signature: "bool → branch", description: "Conditional jump for branching logic." },
  { id: 25, prefix: "MC", name: "ELSE", family: "Control", signature: "→ branch", description: "Alternate branch for conditional logic." },
  { id: 26, prefix: "MC", name: "LOOP", family: "Control", signature: "bool → branch", description: "Bounded iteration construct." },
  { id: 27, prefix: "MC", name: "CALL", family: "Control", signature: "addr → void", description: "Executes another PCD circuit by address." },
  { id: 28, prefix: "MC", name: "RET", family: "Control", signature: "→ i64", description: "Returns the result and closes the circuit." },
  { id: 29, prefix: "MC", name: "HALT", family: "Control", signature: "→ void", description: "Immediate termination of circuit execution." },
  { id: 30, prefix: "MC", name: "NOP", family: "Control", signature: "→ void", description: "No-operation. Consumes one cycle." },
  { id: 31, prefix: "MC", name: "ASSERT", family: "Control", signature: "bool → void", description: "Validates a formal invariant at runtime." },
  { id: 32, prefix: "MC", name: "READ", family: "I/O", signature: "fd → i64", description: "Reads data from a bounded file descriptor." },
  { id: 33, prefix: "MC", name: "WRITE", family: "I/O", signature: "fd, i64 → void", description: "Writes data to a bounded file descriptor." },
  { id: 34, prefix: "MC", name: "OPEN", family: "I/O", signature: "path → fd", description: "Opens a resource with governed permissions." },
  { id: 35, prefix: "MC", name: "CLOSE", family: "I/O", signature: "fd → void", description: "Closes an open file descriptor." },
  { id: 36, prefix: "MC", name: "SEEK", family: "I/O", signature: "fd, i64 → i64", description: "Shifts the offset in a file descriptor." },
  { id: 37, prefix: "MC", name: "FLUSH", family: "I/O", signature: "fd → void", description: "Forces output buffers to be written." },
  { id: 38, prefix: "MC", name: "STDIN", family: "I/O", signature: "→ i64", description: "Reads a single word from standard input." },
  { id: 39, prefix: "MC", name: "STDOUT", family: "I/O", signature: "i64 → void", description: "Writes a single word to standard output." },
  { id: 40, prefix: "MC", name: "LEN", family: "String", signature: "str → i64", description: "Calculates the length of a bounded string." },
  { id: 41, prefix: "MC", name: "CONCAT", family: "String", signature: "str, str → str", description: "Joins two strings into a new bounded string." },
  { id: 42, prefix: "MC", name: "SPLIT", family: "String", signature: "str, str → str[]", description: "Splits a string based on a delimiter." },
  { id: 43, prefix: "MC", name: "TRIM", family: "String", signature: "str → str", description: "Removes whitespace from string boundaries." },
  { id: 44, prefix: "MC", name: "UPPER", family: "String", signature: "str → str", description: "Converts string to uppercase." },
  { id: 45, prefix: "MC", name: "LOWER", family: "String", signature: "str → str", description: "Converts string to lowercase." },
  { id: 46, prefix: "MC", name: "CHAR", family: "String", signature: "i64 → str", description: "Converts code point to a single character." },
  { id: 47, prefix: "MC", name: "ORD", family: "String", signature: "str → i64", description: "Converts character to its code point." },
  { id: 48, prefix: "MC", name: "HASH", family: "Crypto", signature: "bytes → bytes", description: "Deterministic hash of input data." },
  { id: 49, prefix: "MC", name: "ENC", family: "Crypto", signature: "bytes, key → bytes", description: "Encrypts data using a certified key." },
  { id: 50, prefix: "MC", name: "DEC", family: "Crypto", signature: "bytes, key → bytes", description: "Decrypts data using a certified key." },
  { id: 51, prefix: "MC", name: "SIGN", family: "Crypto", signature: "bytes, key → sig", description: "Generates a cryptographic signature." },
  { id: 52, prefix: "MC", name: "VRFY", family: "Crypto", signature: "bytes, sig → bool", description: "Verifies a cryptographic signature." },
  { id: 53, prefix: "MC", name: "RNG", family: "Crypto", signature: "→ i64", description: "Secure random number generation." },
  { id: 54, prefix: "MC", name: "KDF", family: "Crypto", signature: "bytes, salt → key", description: "Key derivation function." },
  { id: 55, prefix: "MC", name: "HMAC", family: "Crypto", signature: "bytes, key → bytes", description: "Keyed-hash message authentication code." },
  { id: 56, prefix: "MC", name: "TIME", family: "System", signature: "→ i64", description: "Retrieves current system time (Unix)." },
  { id: 57, prefix: "MC", name: "ENV", family: "System", signature: "str → str", description: "Reads a system environment variable." },
  { id: 58, prefix: "MC", name: "EXIT", family: "System", signature: "i64 → void", description: "Exits the system with status code." },
  { id: 59, prefix: "MC", name: "SPAWN", family: "System", signature: "addr → pid", description: "Creates a new bounded sub-process." },
  { id: 60, prefix: "MC", name: "WAIT", family: "System", signature: "pid → i64", description: "Waits for a process to terminate." },
  { id: 61, prefix: "MC", name: "RECV", family: "System", signature: "ch → i64", description: "Receives data from a channel." },
  { id: 62, prefix: "MC", name: "SEND", family: "System", signature: "ch, i64 → void", description: "Sends data to a channel." },
  { id: 63, prefix: "MC", name: "LOG", family: "System", signature: "str → void", description: "Writes a system-level audit log entry." },
];

export const EXTENDED_MONOMERS: Monomer[] = [
  { id: 0, prefix: "MX", name: "FADD", family: "Float64", signature: "f64, f64 → f64", description: "Standard floating-point addition." },
  { id: 1, prefix: "MX", name: "FSUB", family: "Float64", signature: "f64, f64 → f64", description: "Standard floating-point subtraction." },
  { id: 2, prefix: "MX", name: "FMUL", family: "Float64", signature: "f64, f64 → f64", description: "Standard floating-point multiplication." },
  { id: 3, prefix: "MX", name: "FDIV", family: "Float64", signature: "f64, f64 → f64", description: "Floating-point division." },
  { id: 4, prefix: "MX", name: "SQRT", family: "Math", signature: "f64 → f64", description: "Square root calculation." },
  { id: 5, prefix: "MX", name: "SIN", family: "Math", signature: "f64 → f64", description: "Trigonometric sine." },
  { id: 6, prefix: "MX", name: "COS", family: "Math", signature: "f64 → f64", description: "Trigonometric cosine." },
  { id: 7, prefix: "MX", name: "LOG2", family: "Math", signature: "f64 → f64", description: "Binary logarithm." },
  { id: 8, prefix: "MX", name: "TCPN", family: "Network", signature: "addr, port → conn", description: "Establishes a bounded TCP connection." },
  { id: 9, prefix: "MX", name: "TCPS", family: "Network", signature: "port → listener", description: "Initializes a TCP server listener." },
  { id: 10, prefix: "MX", name: "HTTP", family: "Network", signature: "req → resp", description: "Sends a governed HTTP request." },
  { id: 11, prefix: "MX", name: "DNS", family: "Network", signature: "str → addr", description: "Resolves a hostname to an IP address." },
  { id: 12, prefix: "MX", name: "TLS", family: "Network", signature: "conn → conn", description: "Wraps a connection with TLS encryption." },
  { id: 13, prefix: "MX", name: "UDP", family: "Network", signature: "addr, bytes → void", description: "Sends a governed UDP packet." },
  { id: 14, prefix: "MX", name: "WS", family: "Network", signature: "url → conn", description: "Establishes a WebSocket connection." },
  { id: 15, prefix: "MX", name: "PING", family: "Network", signature: "addr → i64", description: "Measures network round-trip time." },
  { id: 16, prefix: "MX", name: "PIXEL", family: "Graphics", signature: "x, y, color → void", description: "Sets a pixel on the graphics surface." },
  { id: 17, prefix: "MX", name: "LINE", family: "Graphics", signature: "x1,y1,x2,y2 → void", description: "Draws a bounded line on surface." },
  { id: 18, prefix: "MX", name: "RECT", family: "Graphics", signature: "x,y,w,h → void", description: "Draws a bounded rectangle." },
  { id: 19, prefix: "MX", name: "CIRC", family: "Graphics", signature: "x,y,r → void", description: "Draws a bounded circle." },
  { id: 20, prefix: "MX", name: "TEXT", family: "Graphics", signature: "x,y,str → void", description: "Renders text to the graphics surface." },
  { id: 21, prefix: "MX", name: "IMG", family: "Graphics", signature: "path → pixels", description: "Loads image data into memory." },
  { id: 22, prefix: "MX", name: "BLEND", family: "Graphics", signature: "c1, c2 → color", description: "Blends two colors with transparency." },
  { id: 23, prefix: "MX", name: "CLEAR", family: "Graphics", signature: "→ void", description: "Clears the active graphics surface." },
  { id: 24, prefix: "MX", name: "TONE", family: "Audio", signature: "freq, dur → void", description: "Generates a pure tone frequency." },
  { id: 25, prefix: "MX", name: "PLAY", family: "Audio", signature: "path → void", description: "Plays a governed audio stream." },
  { id: 26, prefix: "MX", name: "REC", family: "Audio", signature: "dur → bytes", description: "Records audio to a memory buffer." },
  { id: 27, prefix: "MX", name: "VOL", family: "Audio", signature: "f64 → void", description: "Sets the system audio output volume." },
  { id: 28, prefix: "MX", name: "MIX", family: "Audio", signature: "a, b → bytes", description: "Mixes two audio streams." },
  { id: 29, prefix: "MX", name: "FFT", family: "Audio", signature: "bytes → f64[]", description: "Fast Fourier Transform on audio data." },
  { id: 30, prefix: "MX", name: "MIDI", family: "Audio", signature: "note → void", description: "Sends a MIDI note command." },
  { id: 31, prefix: "MX", name: "SAMP", family: "Audio", signature: "bytes, i64 → f64", description: "Samples audio data at specific index." },
  { id: 32, prefix: "MX", name: "FOPEN", family: "Filesystem", signature: "path, mode → fd", description: "Opens a file with explicit boundaries." },
  { id: 33, prefix: "MX", name: "FREAD", family: "Filesystem", signature: "fd, size → bytes", description: "Reads bytes from an open file." },
  { id: 34, prefix: "MX", name: "FWRT", family: "Filesystem", signature: "fd, bytes → void", description: "Writes bytes to an open file." },
  { id: 35, prefix: "MX", name: "FSTAT", family: "Filesystem", signature: "path → stat", description: "Retrieves file metadata/status." },
  { id: 36, prefix: "MX", name: "MKDIR", family: "Filesystem", signature: "path → void", description: "Creates a new directory." },
  { id: 37, prefix: "MX", name: "RMDIR", family: "Filesystem", signature: "path → void", description: "Removes an empty directory." },
  { id: 38, prefix: "MX", name: "GLOB", family: "Filesystem", signature: "pattern → path[]", description: "Pattern-based file discovery." },
  { id: 39, prefix: "MX", name: "WATCH", family: "Filesystem", signature: "path → events", description: "Monitors filesystem for changes." },
  { id: 40, prefix: "MX", name: "SPAWN2", family: "Concurrency", signature: "fn → task", description: "Spawns a new task in parallel." },
  { id: 41, prefix: "MX", name: "AWAIT", family: "Concurrency", signature: "task → i64", description: "Binds execution to task completion." },
  { id: 42, prefix: "MX", name: "MUTEX", family: "Concurrency", signature: "→ lock", description: "Initializes a mutual exclusion lock." },
  { id: 43, prefix: "MX", name: "LOCK", family: "Concurrency", signature: "lock → void", description: "Acquires a mutex lock." },
  { id: 44, prefix: "MX", name: "UNLK", family: "Concurrency", signature: "lock → void", description: "Releases a mutex lock." },
  { id: 45, prefix: "MX", name: "CHAN", family: "Concurrency", signature: "→ ch", description: "Initializes a communication channel." },
  { id: 46, prefix: "MX", name: "SELCT", family: "Concurrency", signature: "ch[] → ch", description: "Selects the first available channel." },
  { id: 47, prefix: "MX", name: "YIELD", family: "Concurrency", signature: "→ void", description: "Yields execution to other tasks." },
  { id: 48, prefix: "MX", name: "FFI", family: "Interop", signature: "lib, sym → fn", description: "Foreign Function Interface loader." },
  { id: 49, prefix: "MX", name: "CCAST", family: "Interop", signature: "ptr → i64", description: "Safe pointer-to-integer conversion." },
  { id: 50, prefix: "MX", name: "MARSH", family: "Interop", signature: "val → bytes", description: "Serializes a value to bytes." },
  { id: 51, prefix: "MX", name: "UNMSH", family: "Interop", signature: "bytes → val", description: "Deserializes bytes to a value." },
  { id: 52, prefix: "MX", name: "JSON", family: "Interop", signature: "str → val", description: "Parses JSON string to a value." },
  { id: 53, prefix: "MX", name: "TOJSN", family: "Interop", signature: "val → str", description: "Converts value to JSON string." },
  { id: 54, prefix: "MX", name: "PROTO", family: "Interop", signature: "bytes → val", description: "Deserializes Protobuf data." },
  { id: 55, prefix: "MX", name: "TOPRT", family: "Interop", signature: "val → bytes", description: "Serializes value to Protobuf." },
  { id: 56, prefix: "MX", name: "REGEX", family: "String", signature: "str, pattern → bool", description: "Regular expression matching." },
  { id: 57, prefix: "MX", name: "REPL", family: "String", signature: "str, pat, rep → str", description: "String pattern replacement." },
  { id: 58, prefix: "MX", name: "FMT", family: "String", signature: "str, args → str", description: "Formatted string interpolation." },
  { id: 59, prefix: "MX", name: "PARSE", family: "String", signature: "str → i64", description: "Parses string to 64-bit integer." },
  { id: 60, prefix: "MX", name: "B64E", family: "String", signature: "bytes → str", description: "Base64 encoding." },
  { id: 61, prefix: "MX", name: "B64D", family: "str → bytes", description: "Base64 decoding." },
  { id: 62, prefix: "MX", name: "UTF8", family: "String", signature: "bytes → str", description: "UTF-8 byte-to-string conversion." },
  { id: 63, prefix: "MX", name: "HEXE", family: "String", signature: "bytes → str", description: "Hexadecimal encoding." },
];

/** Demo polymer: OAuth2 Handler */
export const DEMO_POLYMER = {
  name: "OAuth2 Handler",
  phiC: 1,
  core: { 0: 3, 2: 5, 10: 2, 12: 1, 24: 1, 33: 1, 35: 1, 48: 2, 49: 1, 51: 1 },
  extended: { 10: 1, 11: 1, 12: 1, 52: 1, 53: 1 },
} as const;

export const DEMO_POLYMERS = [
  DEMO_POLYMER,
  {
    name: "HTTP Parser",
    phiC: 1,
    core: { 0: 1, 2: 1, 8: 2, 10: 1, 16: 3, 17: 2, 24: 4, 26: 2, 32: 1, 40: 2, 41: 3, 42: 1 },
    extended: { 10: 2, 52: 1, 53: 1, 56: 3, 57: 1 },
  },
  {
    name: "AES-256 Encrypt",
    phiC: 1,
    core: { 2: 8, 8: 4, 10: 12, 12: 4, 13: 4, 26: 10, 48: 1, 49: 1 },
    extended: {},
  },
] as const;
