export interface Monomer {
  id: number;
  prefix: "MC" | "MX";
  name: string;
  family: string;
  signature: string;
}

export const FAMILIES = {
  Arithmetic: "#00e5ff",
  Logic: "#5ce5f0",
  Memory: "#00b8d4",
  Control: "#6b8c40",
  "I/O": "#e0b020",
  String: "#8b7ec8",
  Crypto: "#cc3333",
  System: "#64748b",
} as const;

export type FamilyName = keyof typeof FAMILIES;

export const CORE_MONOMERS: Monomer[] = [
  { id: 0, prefix: "MC", name: "ADD", family: "Arithmetic", signature: "i64, i64 → i64" },
  { id: 1, prefix: "MC", name: "SUB", family: "Arithmetic", signature: "i64, i64 → i64" },
  { id: 2, prefix: "MC", name: "MUL", family: "Arithmetic", signature: "i64, i64 → i64" },
  { id: 3, prefix: "MC", name: "DIV", family: "Arithmetic", signature: "i64, i64 → i64" },
  { id: 4, prefix: "MC", name: "MOD", family: "Arithmetic", signature: "i64, i64 → i64" },
  { id: 5, prefix: "MC", name: "POW", family: "Arithmetic", signature: "i64, i64 → i64" },
  { id: 6, prefix: "MC", name: "NEG", family: "Arithmetic", signature: "i64 → i64" },
  { id: 7, prefix: "MC", name: "ABS", family: "Arithmetic", signature: "i64 → i64" },
  { id: 8, prefix: "MC", name: "AND", family: "Logic", signature: "i64, i64 → i64" },
  { id: 9, prefix: "MC", name: "OR", family: "Logic", signature: "i64, i64 → i64" },
  { id: 10, prefix: "MC", name: "XOR", family: "Logic", signature: "i64, i64 → i64" },
  { id: 11, prefix: "MC", name: "NOT", family: "Logic", signature: "i64 → i64" },
  { id: 12, prefix: "MC", name: "SHL", family: "Logic", signature: "i64, i64 → i64" },
  { id: 13, prefix: "MC", name: "SHR", family: "Logic", signature: "i64, i64 → i64" },
  { id: 14, prefix: "MC", name: "ROL", family: "Logic", signature: "i64, i64 → i64" },
  { id: 15, prefix: "MC", name: "ROR", family: "Logic", signature: "i64, i64 → i64" },
  { id: 16, prefix: "MC", name: "LOAD", family: "Memory", signature: "addr → i64" },
  { id: 17, prefix: "MC", name: "STORE", family: "Memory", signature: "addr, i64 → void" },
  { id: 18, prefix: "MC", name: "ALLOC", family: "Memory", signature: "size → addr" },
  { id: 19, prefix: "MC", name: "FREE", family: "Memory", signature: "addr → void" },
  { id: 20, prefix: "MC", name: "COPY", family: "Memory", signature: "addr, addr, size → void" },
  { id: 21, prefix: "MC", name: "DUP", family: "Memory", signature: "i64 → i64, i64" },
  { id: 22, prefix: "MC", name: "SWAP", family: "Memory", signature: "i64, i64 → i64, i64" },
  { id: 23, prefix: "MC", name: "DROP", family: "Memory", signature: "i64 → void" },
  { id: 24, prefix: "MC", name: "IF", family: "Control", signature: "bool → branch" },
  { id: 25, prefix: "MC", name: "ELSE", family: "Control", signature: "→ branch" },
  { id: 26, prefix: "MC", name: "LOOP", family: "Control", signature: "bool → branch" },
  { id: 27, prefix: "MC", name: "CALL", family: "Control", signature: "addr → void" },
  { id: 28, prefix: "MC", name: "RET", family: "Control", signature: "→ i64" },
  { id: 29, prefix: "MC", name: "HALT", family: "Control", signature: "→ void" },
  { id: 30, prefix: "MC", name: "NOP", family: "Control", signature: "→ void" },
  { id: 31, prefix: "MC", name: "ASSERT", family: "Control", signature: "bool → void" },
  { id: 32, prefix: "MC", name: "READ", family: "I/O", signature: "fd → i64" },
  { id: 33, prefix: "MC", name: "WRITE", family: "I/O", signature: "fd, i64 → void" },
  { id: 34, prefix: "MC", name: "OPEN", family: "I/O", signature: "path → fd" },
  { id: 35, prefix: "MC", name: "CLOSE", family: "I/O", signature: "fd → void" },
  { id: 36, prefix: "MC", name: "SEEK", family: "I/O", signature: "fd, i64 → i64" },
  { id: 37, prefix: "MC", name: "FLUSH", family: "I/O", signature: "fd → void" },
  { id: 38, prefix: "MC", name: "STDIN", family: "I/O", signature: "→ i64" },
  { id: 39, prefix: "MC", name: "STDOUT", family: "I/O", signature: "i64 → void" },
  { id: 40, prefix: "MC", name: "LEN", family: "String", signature: "str → i64" },
  { id: 41, prefix: "MC", name: "CONCAT", family: "String", signature: "str, str → str" },
  { id: 42, prefix: "MC", name: "SPLIT", family: "String", signature: "str, str → str[]" },
  { id: 43, prefix: "MC", name: "TRIM", family: "String", signature: "str → str" },
  { id: 44, prefix: "MC", name: "UPPER", family: "String", signature: "str → str" },
  { id: 45, prefix: "MC", name: "LOWER", family: "String", signature: "str → str" },
  { id: 46, prefix: "MC", name: "CHAR", family: "String", signature: "i64 → str" },
  { id: 47, prefix: "MC", name: "ORD", family: "String", signature: "str → i64" },
  { id: 48, prefix: "MC", name: "HASH", family: "Crypto", signature: "bytes → bytes" },
  { id: 49, prefix: "MC", name: "ENC", family: "Crypto", signature: "bytes, key → bytes" },
  { id: 50, prefix: "MC", name: "DEC", family: "Crypto", signature: "bytes, key → bytes" },
  { id: 51, prefix: "MC", name: "SIGN", family: "Crypto", signature: "bytes, key → sig" },
  { id: 52, prefix: "MC", name: "VRFY", family: "Crypto", signature: "bytes, sig → bool" },
  { id: 53, prefix: "MC", name: "RNG", family: "Crypto", signature: "→ i64" },
  { id: 54, prefix: "MC", name: "KDF", family: "Crypto", signature: "bytes, salt → key" },
  { id: 55, prefix: "MC", name: "HMAC", family: "Crypto", signature: "bytes, key → bytes" },
  { id: 56, prefix: "MC", name: "TIME", family: "System", signature: "→ i64" },
  { id: 57, prefix: "MC", name: "ENV", family: "System", signature: "str → str" },
  { id: 58, prefix: "MC", name: "EXIT", family: "System", signature: "i64 → void" },
  { id: 59, prefix: "MC", name: "SPAWN", family: "System", signature: "addr → pid" },
  { id: 60, prefix: "MC", name: "WAIT", family: "System", signature: "pid → i64" },
  { id: 61, prefix: "MC", name: "RECV", family: "System", signature: "ch → i64" },
  { id: 62, prefix: "MC", name: "SEND", family: "System", signature: "ch, i64 → void" },
  { id: 63, prefix: "MC", name: "LOG", family: "System", signature: "str → void" },
];

export const EXTENDED_MONOMERS: Monomer[] = [
  { id: 0, prefix: "MX", name: "FADD", family: "Float64", signature: "f64, f64 → f64" },
  { id: 1, prefix: "MX", name: "FSUB", family: "Float64", signature: "f64, f64 → f64" },
  { id: 2, prefix: "MX", name: "FMUL", family: "Float64", signature: "f64, f64 → f64" },
  { id: 3, prefix: "MX", name: "FDIV", family: "Float64", signature: "f64, f64 → f64" },
  { id: 4, prefix: "MX", name: "SQRT", family: "Math", signature: "f64 → f64" },
  { id: 5, prefix: "MX", name: "SIN", family: "Math", signature: "f64 → f64" },
  { id: 6, prefix: "MX", name: "COS", family: "Math", signature: "f64 → f64" },
  { id: 7, prefix: "MX", name: "LOG2", family: "Math", signature: "f64 → f64" },
  { id: 8, prefix: "MX", name: "TCPN", family: "Network", signature: "addr, port → conn" },
  { id: 9, prefix: "MX", name: "TCPS", family: "Network", signature: "port → listener" },
  { id: 10, prefix: "MX", name: "HTTP", family: "Network", signature: "req → resp" },
  { id: 11, prefix: "MX", name: "DNS", family: "Network", signature: "str → addr" },
  { id: 12, prefix: "MX", name: "TLS", family: "Network", signature: "conn → conn" },
  { id: 13, prefix: "MX", name: "UDP", family: "Network", signature: "addr, bytes → void" },
  { id: 14, prefix: "MX", name: "WS", family: "Network", signature: "url → conn" },
  { id: 15, prefix: "MX", name: "PING", family: "Network", signature: "addr → i64" },
  { id: 16, prefix: "MX", name: "PIXEL", family: "Graphics", signature: "x, y, color → void" },
  { id: 17, prefix: "MX", name: "LINE", family: "Graphics", signature: "x1,y1,x2,y2 → void" },
  { id: 18, prefix: "MX", name: "RECT", family: "Graphics", signature: "x,y,w,h → void" },
  { id: 19, prefix: "MX", name: "CIRC", family: "Graphics", signature: "x,y,r → void" },
  { id: 20, prefix: "MX", name: "TEXT", family: "Graphics", signature: "x,y,str → void" },
  { id: 21, prefix: "MX", name: "IMG", family: "Graphics", signature: "path → pixels" },
  { id: 22, prefix: "MX", name: "BLEND", family: "Graphics", signature: "c1, c2 → color" },
  { id: 23, prefix: "MX", name: "CLEAR", family: "Graphics", signature: "→ void" },
  { id: 24, prefix: "MX", name: "TONE", family: "Audio", signature: "freq, dur → void" },
  { id: 25, prefix: "MX", name: "PLAY", family: "Audio", signature: "path → void" },
  { id: 26, prefix: "MX", name: "REC", family: "Audio", signature: "dur → bytes" },
  { id: 27, prefix: "MX", name: "VOL", family: "Audio", signature: "f64 → void" },
  { id: 28, prefix: "MX", name: "MIX", family: "Audio", signature: "a, b → bytes" },
  { id: 29, prefix: "MX", name: "FFT", family: "Audio", signature: "bytes → f64[]" },
  { id: 30, prefix: "MX", name: "MIDI", family: "Audio", signature: "note → void" },
  { id: 31, prefix: "MX", name: "SAMP", family: "Audio", signature: "bytes, i64 → f64" },
  { id: 32, prefix: "MX", name: "FOPEN", family: "Filesystem", signature: "path, mode → fd" },
  { id: 33, prefix: "MX", name: "FREAD", family: "Filesystem", signature: "fd, size → bytes" },
  { id: 34, prefix: "MX", name: "FWRT", family: "Filesystem", signature: "fd, bytes → void" },
  { id: 35, prefix: "MX", name: "FSTAT", family: "Filesystem", signature: "path → stat" },
  { id: 36, prefix: "MX", name: "MKDIR", family: "Filesystem", signature: "path → void" },
  { id: 37, prefix: "MX", name: "RMDIR", family: "Filesystem", signature: "path → void" },
  { id: 38, prefix: "MX", name: "GLOB", family: "Filesystem", signature: "pattern → path[]" },
  { id: 39, prefix: "MX", name: "WATCH", family: "Filesystem", signature: "path → events" },
  { id: 40, prefix: "MX", name: "SPAWN2", family: "Concurrency", signature: "fn → task" },
  { id: 41, prefix: "MX", name: "AWAIT", family: "Concurrency", signature: "task → i64" },
  { id: 42, prefix: "MX", name: "MUTEX", family: "Concurrency", signature: "→ lock" },
  { id: 43, prefix: "MX", name: "LOCK", family: "Concurrency", signature: "lock → void" },
  { id: 44, prefix: "MX", name: "UNLK", family: "Concurrency", signature: "lock → void" },
  { id: 45, prefix: "MX", name: "CHAN", family: "Concurrency", signature: "→ ch" },
  { id: 46, prefix: "MX", name: "SELCT", family: "Concurrency", signature: "ch[] → ch" },
  { id: 47, prefix: "MX", name: "YIELD", family: "Concurrency", signature: "→ void" },
  { id: 48, prefix: "MX", name: "FFI", family: "Interop", signature: "lib, sym → fn" },
  { id: 49, prefix: "MX", name: "CCAST", family: "Interop", signature: "ptr → i64" },
  { id: 50, prefix: "MX", name: "MARSH", family: "Interop", signature: "val → bytes" },
  { id: 51, prefix: "MX", name: "UNMSH", family: "Interop", signature: "bytes → val" },
  { id: 52, prefix: "MX", name: "JSON", family: "Interop", signature: "str → val" },
  { id: 53, prefix: "MX", name: "TOJSN", family: "Interop", signature: "val → str" },
  { id: 54, prefix: "MX", name: "PROTO", family: "Interop", signature: "bytes → val" },
  { id: 55, prefix: "MX", name: "TOPRT", family: "Interop", signature: "val → bytes" },
  { id: 56, prefix: "MX", name: "REGEX", family: "String", signature: "str, pattern → bool" },
  { id: 57, prefix: "MX", name: "REPL", family: "String", signature: "str, pat, rep → str" },
  { id: 58, prefix: "MX", name: "FMT", family: "String", signature: "str, args → str" },
  { id: 59, prefix: "MX", name: "PARSE", family: "String", signature: "str → i64" },
  { id: 60, prefix: "MX", name: "B64E", family: "String", signature: "bytes → str" },
  { id: 61, prefix: "MX", name: "B64D", family: "String", signature: "str → bytes" },
  { id: 62, prefix: "MX", name: "UTF8", family: "String", signature: "bytes → str" },
  { id: 63, prefix: "MX", name: "HEXE", family: "String", signature: "bytes → str" },
];

/** Demo polymer: OAuth2 Handler */
export const DEMO_POLYMER = {
  name: "OAuth2 Handler",
  phiC: 1,
  core: { 0: 3, 2: 5, 10: 2, 12: 1, 24: 1, 33: 1, 35: 1, 48: 2, 49: 1, 51: 1 },
  extended: { 10: 1, 11: 1, 12: 1, 52: 1, 53: 1 },
} as const;

export const DEMO_POLYMERS = [
  DEMO_POLYMER,
  {
    name: "HTTP Parser",
    phiC: 1,
    core: { 0: 1, 2: 1, 8: 2, 10: 1, 16: 3, 17: 2, 24: 4, 26: 2, 32: 1, 40: 2, 41: 3, 42: 1 },
    extended: { 10: 2, 52: 1, 53: 1, 56: 3, 57: 1 },
  },
  {
    name: "AES-256 Encrypt",
    phiC: 1,
    core: { 2: 8, 8: 4, 10: 12, 12: 4, 13: 4, 26: 10, 48: 1, 49: 1 },
    extended: {},
  },
] as const;
